# Generated by Django 2.2 on 2018-10-29 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TasksDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('assignee', models.CharField(max_length=20)),
                ('duedate', models.DateField()),
                ('reporter', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=20)),
                ('updatedate', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tasksdb',
            },
        ),
    ]
