# Generated by Django 2.1.2 on 2018-10-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasks', models.CharField(max_length=250)),
                ('tasks_title', models.CharField(max_length=500)),
                ('tasks_logo', models.CharField(max_length=1000)),
            ],
        ),
    ]
